FORMAT: 1A

# Texter API
This document describes the various API calls you can make with the texter.

# Group Service Health
## GET /health-check
This call returns a simple structure that determines whether or not the API is recieving traffic. It doesn't reason about the availability of the service, only if you can ask it for this route.

+ Response 200 (application/json)
```
{
    "gtg": true 
}
```

# Group Sending a Message
There's really only a single method you can use for sending a message to someone. This message can have replacement tags in it as described below:

{{targets.title}} => The user's congressional representative's long title.
{{targets.full_name}} => The user's congressional representative's full name.
{{targets.phone}} => The user's congressional representative's office number.
{{targets.last_name}} => The user's congressional representative's last name.
{{targets.short_title}} => The user's congressional representative's short title.

## POST /messages
Post to this route in order to ask the texter to send an SMS message to the target with any tags replaced.
+ Attributes (Target)
+ Request (application/json)
+ Response 202 (application/json)
+ Response 400 (application/json)
    + Attributes (Error Struct)

# Data Structures
## Error Struct (object)
+ status: 400 (number)
+ message: You did it wrong (string)

## Campaign (object)
+ _id: My Campaign (string)
+ body: My cool {{ replacable }} message (string)
+ createdFrom: 123 (string)
+ audience: 1 (number)

## Target (object)
+ phonenumber: 4045551234 (string)
+ usdistrict: GA_07 (string)
+ message: Cool dude. (string)